version: 1.0.0.{build}
configuration:
  - Debug
  - Release
clone_depth: 10
environment:
  matrix:
    - VS_VERSION: 10
      CMAKE_GENERATOR: Visual Studio 10 2010
      PlatformToolset: v100
    - VS_VERSION: 14
      CMAKE_GENERATOR: Visual Studio 14 2015
      PlatformToolset: v140_xp
before_build:
  - git submodule update --init --recursive
  - ps: . $Env:APPVEYOR_BUILD_FOLDER/ci/appveyor/check_release.ps1
  - ps: . $Env:APPVEYOR_BUILD_FOLDER/ci/appveyor/before_build.ps1
build_script:
  - ps: . $Env:APPVEYOR_BUILD_FOLDER/ci/appveyor/build.ps1


deploy:
    - provider: GitHub
      auth_token:
          secure: RWe6hwCcgBdklaYvjB62kzhKn7yDBJdqoDDKYViShaEV9HkJ75HbawsBcGBimRUu
      on:
          ReleaseBuild: true        # deploy on release push only

    - provider: BinTray
      username: asarium
      api_key:
          secure: 2lHma1ZreuB4CCE5hSdp+gqFjCMzUDj3tVJhP+D6EyF5wIVMLlwXFrISwnYu1kJi
      subject: scp-fs2open
      repo: FSO
      package: nightly
      version: $(VersionName)
      publish: true
      override: true
      on:
          NightlyBuild: true        # deploy on nightly push only